version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./services/db_service/init_scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

  back:
    build:
      context: ./services/
      dockerfile: ./back/Dockerfile
    command: poetry run app -V
    container_name: back
    restart: unless-stopped
    volumes:
      - ./services/back/:/app/
      - ./logging/:/app/back/logging/
    env_file:
      - ./.env
    ports:
      - 8004:8000
    depends_on:
      - scraper
      - processor_images
      - db_service

  scraper:
    build:
      context: ./services/
      dockerfile: ./scraper/Dockerfile
    command: poetry run app -V
    container_name: scraper
    restart: unless-stopped
    volumes:
      - ./services/scraper/:/app/
      - ./all_saved_imgs/saved_imgs/:/app/saved_imgs/
      - ./logging/:/app/scraper/logging/
    env_file:
      - ./.env
    expose:
      - 8000

  processor_images:
    build:
      context: ./services/
      dockerfile: ./processor_images/Dockerfile
    command: poetry run app -V
    container_name: processor_images
    restart: unless-stopped
    volumes:
      - ./services/processor_images/:/app/
      - ./all_saved_imgs/highlighted_imgs/:/app/highlighted_imgs/
      - ./all_saved_imgs/saved_imgs/:/app/saved_imgs/
      - ./logging/:/app/processor_images/logging/
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - db_service

  cv2_img_search:
    build:
      context: ./services/
      dockerfile: ./cv2_img_search/Dockerfile
    command: poetry run app -V
    container_name: cv2_img_search
    restart: unless-stopped
    volumes:
      - ./services/cv2_img_search/:/app/
      - ./all_saved_imgs/highlighted_imgs/:/app/highlighted_imgs/
      - ./logging/:/app/cv2_img_search/logging/
    env_file:
      - ./.env
    expose:
      - 8000

  db_service:
    build:
      context: ./services/
      dockerfile: ./db_service/Dockerfile
    command: poetry run app -V
    container_name: db_service
    restart: unless-stopped
    volumes:
      - ./services/db_service/:/app/
      - ./logging/:/app/db_service/logging/
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: